### ISSUE TITLE
Features reimplementation

### ISSUE THREAD

**Issue by Kasia1403** [Gilded-Games/The-Aether-II#131]
Could You ( mod author ) reimplement old versions features like slimes as companion mobs and Frostpine Totem ( also as companion mob ) and Continuum Orbs ( Minecraft 1.12.2 ) ?

**Comment by Alexmasonseals** [comment]
they will comeback in some way in aether highlands, as for aether 1 well no, because aether 1 is not a port form genesis of the void,
its a port from the original aether mod from 2010 -2011 ish which didn't had the content that you mentioned, also aether 1 is content locked so the devs will not add more content like the companions you said.

**Comment by Kasia1403** [comment]
Many features are STILL not implemented. When will You add them ?

**Comment by Kasia1403** [comment]
Why still no update for MC 1.12.2 ? I want pink Swet and Frostpine Totem. Could You add it ?

**Comment by MagmaBro123** [comment]
> Why still no update for MC 1.12.2 ? I want pink Swet and Frostpine Totem. Could You add it ?

Read Alex's comment. Aether 1 is being ported to 1.18 (And will probably release on 1.19). Aether II will get companions too, hopefully.1.12.2 is dead.

**Comment by Kasia1403** [comment]
> > Why still no update for MC 1.12.2 ? I want pink Swet and Frostpine Totem. Could You add it ?
> 
> Read Alex's comment. Aether 1 is being ported to 1.18 (And will probably release on 1.19). Aether II will get companions too, hopefully. 1.12.2 is dead.
> 
> Join the Discord for news about the mod. https://discord.gg/aethermod

But anyway pink Swet and Frostpine Totem in MC 1.12.2 please !

**Comment by bconlon1** [comment]
This issue tracker isn't a place to request for features we haven't gotten around to reimplementing yet or may not reimplement.
