### ISSUE TITLE
Nothing in skyroot chest

### ISSUE THREAD

**Issue by kinggodMC** [Gilded-Games/The-Aether-II#132]
In my case, I'm using version Aether II - Highlands update 0.3.0
When I move to the aether, there is a lot of buildings and there are skyroot chests in buildings but there isn't any items inside of skyroot  chests. Is that bug?

**Comment by devilbringer** [comment]
No it's not a bug we just never got any loot items implemented into the structures, they were mostly for testing generation. Closing this issue.
