### ISSUE TITLE
The only Irradiated thing that works are Irradiated Chunks

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether-II#155]
All of the otherones just cool into Irradiated Dust

**Comment by 74HC14** [comment]
In my experience, the weapon, armour, and tool will sometimes cool into random weapons, armour, and tools respectively, and of random Aether materials. As well as producing dust. Guess I didn't see what the chunks turned into. I suspect the other items wouldn't be too hard to add also, but considering these items can't be found in the game, nor is there any structures to find them in besides watchtowers, I doubt it's high on the priority list.

That said, I am aiming to use 1.12.2's Aether II Highlands to make a modpack that uses some unused items and disables unfinished features, so it would be somewhat helpful if this feature was somewhat completed to that end.

**Comment by Builderdog841** [comment]
I am playing the 0.3.1 Testbuilds and it´s only buggy there (you can get the Irradiated things in that version)
