### ISSUE TITLE
Returning from the Aether drops me in random locations, Aerther portal glitches

### ISSUE THREAD

**Issue by Damascus117** [Gilded-Games/The-Aether-II#158]
I'm currently using the Aether version that comes with Better Minecraft [FABRIC] 1.17.1

I'm having a problem with returning from the Aether sending me to completely random locations in the Overworld. I read that when you jump off the islands in the Aether, it should send you to directly over your portal in the Overworld. Instead, I appear in the sky at a seemingly random location within 200-300 blocks of my portal.

The return portal is a little more consistent, but still buggy. It doesn't send me back to the portal I created, but creates a new portal about 100 blocks away. Except for one time most recently, it instead spawned me in the middle of a wall underground, about 400 blocks from spawn, and it didn't even create a new portal.

One last interesting glitch happened when I tried to enter my Aether portal in the Overworld. It didn't send me to the Aether at all, but instead teleported me some 10,000 blocks away in the Overworld to an extremely distant point from my base.

**Comment by Mugman2000** [comment]
1. The Aether mod you're using is "Paradise Lost - The Aether Reborn" not "Aether II".
2. Said mod is only recognized by Gilded Games, not created by them.
