### ISSUE TITLE
[1.7.10] tile.Aercloud5.name generates

### ISSUE THREAD

**Issue by Mugman2000** [Gilded-Games/The-Aether-II#159]
In 1.6 of Aether II for 1.7.10, occasionally a small aercloud of tile.Aercloud5.name will generate.
My best guess as to why this happens is that at some point during development Purple Aerclouds were once the same block ID as the other Aerclouds, then when they were split the generation code wasn't deleted.

Also to anyone wondering: tile.Aercloud5.name acts and looks like a regular Cold Aercloud.
(also unrelated note: if and when you fix this, please don't remove the Frosty Music Disc like you did in 1.12.2, and it would be nice if you ported it to 1.12.2. Why did you remove it anyways?)

**Comment by bconlon1** [comment]
1.7.10 won't be receiving any updates so this won't be fixed. The music disc could return, a lot of stuff just wasn't re-added for 1.12, not necessarily removed, but nothing is set in stone.
