### ISSUE TITLE
1.12.2 Aether 2 and Orbis Library Crash

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [Gilded-Games/The-Aether-II#161]
Hi, I'm using the latest version of Aether 2 and my game keeps crashing. I've talked with some other people about this issue and they've said that an older version of Orbis Library was being used in the embedded library for Aether 2 . I was wondering if you could help in fixing this issue?

Here is the Crash Report: https://paste.ee/p/Ilyoj

**Comment by MagmaBro123** [comment]
Aether 2 on 1.12 is very outdated and unfinished.

You should be using Aether Legacy along with its few addons, which are better.

**Comment by bconlon1** [comment]
Did you download Orbis Lib from Curseforge? Or are you only using the one that comes with Aether 2 itself.

**Comment by bconlon1** [comment]
I also do not see anything that immediately points to this being caused by Orbis Lib in the crash report. If you do not have an extra version of Orbis Lib installed and only are using the one that comes prepackaged with Aether 2, try to see if Aether 2 crashes on its own, and if it doesn't, begin adding mods back into the pack until the mod causing the crash is determined.

**Comment by 23KiaraMinecraft** [comment]
![2022-02-02 (1)](https://user-images.githubusercontent.com/76888993/152253141-1cdf5b1b-ca45-4196-a5e2-1f33e1086404.png)

**Comment by 23KiaraMinecraft** [comment]
Starting from 1/19, all the mods from there are the ones I added.

**Comment by bconlon1** [comment]
I wouldn't be able to tell which mods might be causing the issue specifically, so all I can suggest is testing removing those recently added ones on your own, if they are what's causing the crash and Orbis and Aether run fine together on their own.

**Comment by 23KiaraMinecraft** [comment]
So, I figured it out, Aether 2 crashes with mods that load Mixin into the game.

**Comment by bconlon1** [comment]
That may be a Phosphor issue, try downloading the latest 1.12 version of Phosphor from https://www.curseforge.com/minecraft/mc-mods/phosphor-forge
