### ISSUE TITLE
Aether 2 and Security Craft Crash

### ISSUE THREAD

**Issue by 23KiaraMinecraft** [Gilded-Games/The-Aether-II#162]
So, I'm using this version of Security Craft for 1.12.2 (https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3577171) and the latest version of Aether 2 crashes when any mod that loads Mixen into the game is added. I would use the other version of Security Craft (https://www.curseforge.com/minecraft/mc-mods/security-craft/files/3577164) but my game crashes with that one as well and it is completely unrelated to the problem I'm having now.

**Comment by bconlon1** [comment]
Please look at the reply I left on the previous ticket you opened.
