### ISSUE TITLE
update to 1.18.1? 

### ISSUE THREAD

**Issue by ozma6464** [Gilded-Games/The-Aether-II#164]
Could this please be updated to 1.18.1?

**Comment by ZolaKluke** [comment]
They're planning on doing that once Aether 1 is finished being ported and then they're gonna base the new Aether 2 port off of the Aether 1 1.18.1 port's code

**Comment by bconlon1** [comment]
Please don't use our issue tracker for this. We plan on porting to 1.18 in the future.

**Comment by ZolaKluke** [comment]
@ozma6464 Here will provide more info: https://discord.gg/njXKBqveey
