### ISSUE TITLE
Circle builds not working

### ISSUE THREAD

**Issue by joeyoropesa-dev** [Gilded-Games/The-Aether-II#177]
We can download from Circle dev builds of this mod for latest Minecraft version. The status says only not run and also run failed on many attempts by contributors there. I don't have rw access there so I wasn't able to try to re-run the jobs but anyway I think it will not work if the problem is in the code itself.

Please, check workflows ability for standard users and try to re-run the job after the fix so we can download Aether II dev edge versions on our latest Minecraft versions.

**Comment by bconlon1** [comment]
Aether II is not in active development yet, the CircleCI builds are not ready.

**Comment by Kasia0314** [comment]
What is CircleCI ?

**Comment by SteveJDM** [comment]
> What is CircleCI ?

CircleCI is what the team is using to compile test builds for projects like Aether 1 and the Genesis addon. Im not sure exactly how it works but to my limited knowledge, it compiles the github .zip's into .jar's that can be used as mods.
