### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Kasia0314** [Gilded-Games/The-Aether-II#180]
When the next update for Minecraft 1.12.2 ? Are dungeons generating in version 0.3.0 ?

**Comment by Kasia0314** [comment]
What is Back Log ?

**Comment by Aethyus** [comment]
> When the next update for Minecraft 1.12.2 ? Are dungeons generating in version 0.3.0 ?

The mod is in pause currently and the new versions will only be playable in recent updates of Minecraft, so no more new 1.12.2 Aether II versions. No, the dungeons are not generating in the Aether II: Highlands 1.12.2.

**Comment by Kasia0314** [comment]
@Aethyus So I can't wait until You will change Your mind and will update also 1.12.2 version.

**Comment by bconlon1** [comment]
Do not use our issue tracker for questions.
