### ISSUE TITLE
Plans for 1.18.2 and up?

### ISSUE THREAD

**Issue by LauftaProufundus** [Gilded-Games/The-Aether-II#181]
As a deep fan of the Aether mod - let's face it, a staple in practically every gamer's childhood - I'd really love to see additional versions of this mod and know that other players feel the same.

**Comment by bconlon1** [comment]
We plan to update the mod to 1.20 in the future.

**Comment by LauftaProufundus** [comment]
And 1.18.2?

**Comment by bconlon1** [comment]
There are no plans for 1.18.2.
