### ISSUE TITLE
Please don't include an old Phosphor version

### ISSUE THREAD

**Issue by TheComputerizer** [Gilded-Games/The-Aether-II#182]
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

N/A

### What Type of Bug Is This?

Crash

### Forge Version

14.23.5.2860

### The Aether II Version

0.3.0

### Is This Bug a Conflict With Another Mod?

[Alfheim Lighting Engine](https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine)

### Crash Report (if applicable)

https://mclo.gs/WjZ8W2c

### Steps to Reproduce

- Have Aether 2 & Alfheim installed at the same time

### What You Expect To Happen

N/A

### What Actually Happened

N/A

### Additional Details

If phosphor is really needed it would be a lot better to keep it as an external dependency with a minimum version requirement instead of including the jar so people are not forced to use an older phosphor version with more issues instead of a newer fork that is still being maintained. 

If 1.12.2 is not really supported anymore I would be fine with making a PR, though the orbis lib jar does not seem to have any working public links that I am aware of

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
1.12 is unsupported.

**Comment by KorewaLidesu** [comment]
Would you like to accept PR?
