### ISSUE TITLE
Feature: Damage Types

### ISSUE THREAD

**Issue by OzPayn** [Gilded-Games/The-Aether-II#200]
Slash Damage (Blue) - Swords + Sweeping
Impact Damage (Yellow) - Hammers + Shock
Pierce Damage (Red) - Spears + Stab
![image](https://github.com/The-Aether-Team/The-Aether-II/assets/6759864/5648599f-ed81-416b-b9db-5eb40ab13a1e)
![image](https://github.com/The-Aether-Team/The-Aether-II/assets/6759864/039fd609-1705-4994-a043-71dda0016d23)

**Comment by bconlon1** [comment]
Likely going to make damage type stats data-driven, with registries for both Damage and Resistance. Items would be attached to Damage and Entity Types would be attached to Resistance.
