### ISSUE TITLE
Feature: Irradiated Block and Items

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether-II#298]

**Comment by Builderdog841** [comment]
![irradiated_dust](https://github.com/user-attachments/assets/d3721f41-46bf-4734-b6f9-ac285d0ce403)
![irradiated_armor](https://github.com/user-attachments/assets/fa5e9d8d-e92c-4e7b-9aab-2040f26fe546)
![irradiated_chunk](https://github.com/user-attachments/assets/737878b6-643d-4cf1-9f70-602529ee827c)
![irradiated_tool](https://github.com/user-attachments/assets/f0caf1b7-5e32-4c4c-a1ba-183d44ff4956)
![irradiated_sword](https://github.com/user-attachments/assets/4cd84aa2-4678-472f-b207-e44ef454cc1e)

**Comment by Builderdog841** [comment]
![irradiated_dust_block](https://github.com/user-attachments/assets/b87e2998-6f99-4717-9488-9c47e6254987)
(Animated Texture, needs Interpolation)

**Comment by Builderdog841** [comment]
[Irradiated Stuff.zip](https://github.com/user-attachments/files/17893843/Irradiated.Stuff.zip)
