### ISSUE TITLE
Bug: Skyroot Beds (and /weather command) not clearing weather

### ISSUE THREAD

**Issue by VaraHunter682** [Gilded-Games/The-Aether-II#324]
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

20.4.234

### The Aether II Version

1.20.4-001

### Steps to Reproduce

wait for it to rain/snow, then type "/weather  clear" in chat or sleep in a Skyroot Bed

### What You Expect To Happen

Based on Vanilla behavior, this should've cleared the weather.

### What Actually Happened

Both do nothing, it still rains.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Builderdog841** [comment]
You need to write /execute in minecraft:overworld run weather clear. This seems to be a hardcoded Vanilla flaw (I think) so we might need to add a new command

**Comment by VaraHunter682** [comment]
ah ok

**Comment by bconlon1** [comment]
code to add
```    @Nullable
    public static Long finishSleep(LevelAccessor level, long newTime) {
        if (level instanceof ServerLevel && level.dimensionType().effectsLocation().equals(AetherDimensions.AETHER_DIMENSION_TYPE.location())) {
            ServerLevelAccessor serverLevelAccessor = (ServerLevelAccessor) level;
            serverLevelAccessor.aether$getServerLevelData().setRainTime(0);
            serverLevelAccessor.aether$getServerLevelData().setRaining(false);
            serverLevelAccessor.aether$getServerLevelData().setThunderTime(0);
            serverLevelAccessor.aether$getServerLevelData().setThundering(false);

            long time = newTime + 48000L;
            return time - time % (long) AetherDimensions.AETHER_TICKS_PER_DAY;
        }
        return null;
    }```
