### ISSUE TITLE
Bug: <Crash while entering in the Nether>

### ISSUE THREAD

**Issue by NAPPUS** [Gilded-Games/The-Aether-II#401]
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Crash

### Forge Version

21.0.167

### The Aether II Version

0.0.1

### Is This Bug a Conflict With Another Mod?

no

### Client Log

<script src="https://gist.github.com/NAPPUS/14e86c0f6b66f970854c6be4e455c277.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/NAPPUS/df152b077410e022c505c6c093b49352.js"></script>

### Steps to Reproduce

Having the Aether II mod installed, everytime the player enter in the Nether, the game crash.

### What You Expect To Happen

To enter in the Nether without crashing.

### What Actually Happened

The game crash as soon as the Nether is loaded.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Jonathing** [comment]
Hello. Yearly comment from Jonathan because I am bored and have limited cellular data 😎👍

This crash appears to be from casting an entity to a player without doing a prior check. I haven't read the code itself but I've had issues in the past where capabilities would sometimes be sent for the incorrect class type.
