### ISSUE TITLE
Bug: skyroot dupe glitch

### ISSUE THREAD

**Issue by SteveJDM** [Gilded-Games/The-Aether-II#442]
### What Feature Types Apply to This Bug?

Item, System

### What Type of Bug Is This?

Design

### Forge Version

21.0.167

### The Aether II Version

1.21-0.0.1

### Steps to Reproduce

place down a block and break it with its appropriate skyroot tool. 

### What You Expect To Happen

player based blocks shouldn't dupe

### What Actually Happened

player placed blocks will dupe

### Additional Details

https://youtu.be/gCP56_bcSZc[https://youtu.be/gCP56_bcSZc](url)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Builderdog841** [comment]
Skyroots Ability was changed, player based blocks can now be duped, they just don't 100% of the time and it only works on certain blocks, iirc sometimes they can even drop 3 blocks. That's why the tooltip has been changed to "Increased yield"

**Comment by SteveJDM** [comment]
which blocks are in the list?

**Comment by Builderdog841** [comment]
Mostly just basic natural Aether Blocks, like logs, dirt, stone, ambrosium etc

**Comment by Builderdog841** [comment]
It uses a tag so you should be able to check the list via JEI
