### ISSUE TITLE
Bug: Block of Arkenium cannot be mined with a pickaxe

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether-II#445]
### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

21.0.167

### The Aether II Version

0.0.1

### Steps to Reproduce

1. Place a block of arkenium.
2. Try to mine it with a gravitite pickaxe.

### What You Expect To Happen

I expect to be able to mine it and pick it back up.

### What Actually Happened

The block is not considered as breakable with a pickaxe and thus takes forever to mine.

### Additional Details

![2024-10-17_17 35 17](https://github.com/user-attachments/assets/ce00454f-ddd0-4f5c-9f26-911f2d04b259)
Please fix asap

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Builderdog841** [comment]
Issue can be closed
