### ISSUE TITLE
Bug: Aerclouds block sunlight

### ISSUE THREAD

**Issue by Cinex20** [Gilded-Games/The-Aether-II#465]
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

21.1.80

### The Aether II Version

0.0.1

### Steps to Reproduce

Spawn a cockatrice under an aercloud during the day.

### What You Expect To Happen

I expect the cockatrice to burn in daylight.

### What Actually Happened

The aerclouds block access to the sky, preventing the cockatrice from burning, even though it's standing in broad daylight.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
Intentional; this is necessary for the cloud sea and underground areas to function
