### ISSUE TITLE
Bug: only blue swets spawn

### ISSUE THREAD

**Issue by SteveJDM** [Gilded-Games/The-Aether-II#466]
### What Feature Types Apply to This Bug?

Entity

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

21.1.90

### The Aether II Version

1.21-0.0.1 (build 1185)

### Is This Bug a Conflict With Another Mod?

no

### Steps to Reproduce

wait for swets to spawn. only blue ones ever do.

### What You Expect To Happen

all varients of swet would spawn, including: green, blue, purple, golden, and white.

### What Actually Happened

only blue swets spawn

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment]
there are no swet variants yet
